=== Ivelian/M04UF1/character.dtd
<!ELEMENT character (name, surname?, age, race, class, gender, height, weight, TieneLaESO?)>

<!ELEMENT name (#PCDATA)>
<!ELEMENT surname (#PCDATA)>
<!ELEMENT age EMPTY>
<!ELEMENT race (#PCDATA)>
<!ELEMENT gender (#PCDATA)>
<!ELEMENT height EMPTY>
<!ELEMENT weight EMPTY>
<!ELEMENT language (#PCDATA)>
<!ELEMENT TieneLaESO EMPTY>


<!ATTLIST character id_character CDATA #REQUIRED>
<!ATTLIST age years CDATA #REQUIRED>
<!ATTLIST gender abbrev CDATA #REQUIRED>
<!ATTLIST height cm CDATA #REQUIRED>
<!ATTLIST weight kg CDATA #REQUIRED>
<!ATTLIST languagee abbrev CDATA #REQUIRED>

=== Ivelian/M04UF1/character.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE character SYSTEM "character.dtd">
<character>
        <name>Eustaqui</name>
        <surname>Mendoza</surname>
        <!-- COMENTARIO -->
        <age>longevity="197"</age>
        <race>Enano</race>
        <class>Artificiero</class>
        <gender abbrev="N">Non-Binary</gender>
        <TieneLaESO latiene="sÃ­" />
</character>
